# Generated by Django 4.2.5 on 2023-09-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('1', 'Нужно сделать'), ('2', 'Запланировано'), ('3', 'В работе у меня'), ('4', 'В работе не у меня'), ('5', 'Сегодня'), ('6', 'Выполнено')], max_length=30, verbose_name='Статус'),
        ),
    ]
