# Generated by Django 4.2.5 on 2023-09-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Нужно сделать', 'Нужно сделать'), ('Запланировано', 'Запланировано'), ('В работе у меня', 'В работе у меня'), ('В работе не у меня', 'В работе не у меня'), ('Сегодня', 'Сегодня'), ('Выполнено', 'Выполнено')], default='Нужно сделать', max_length=30, verbose_name='Статус'),
        ),
    ]
