# Generated by Django 4.2.5 on 2023-09-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateField(null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='task',
            name='due_dt',
            field=models.DateField(null=True, verbose_name='Сделать до'),
        ),
        migrations.AddField(
            model_name='task',
            name='person',
            field=models.CharField(max_length=100, null=True, verbose_name='Участник'),
        ),
        migrations.AlterField(
            model_name='task',
            name='desc_text',
            field=models.TextField(max_length=255, verbose_name='Описание задачи'),
        ),
    ]
