# Generated by Django 4.2.5 on 2023-09-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_due_dt_alter_task_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='desc_text',
            field=models.CharField(max_length=255, verbose_name='Описание задачи'),
        ),
    ]
