# Generated by Django 4.2.5 on 2023-09-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_desc_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='person',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Участник'),
        ),
    ]
